### ISSUE TITLE
Is the Application interface too big?

### ISSUE THREAD

**Issue by meling** [tendermint/abci#137]
Please pardon my ignorance, having just started looking at tendermint and abci. I was looking at the `Application` interface:
```go
type Application interface {
	// Info/Query Connection
	Info(RequestInfo) ResponseInfo                   // Return application info
	SetOption(key string, value string) (log string) // Set application option
	Query(RequestQuery) ResponseQuery                // Query for state

	// Mempool Connection
	CheckTx(tx []byte) Result // Validate a tx for the mempool

	// Consensus Connection
	InitChain(RequestInitChain)              // Initialize blockchain with validators and other info from TendermintCore
	BeginBlock(RequestBeginBlock)            // Signals the beginning of a block
	DeliverTx(tx []byte) Result              // Deliver a tx for full processing
	EndBlock(height uint64) ResponseEndBlock // Signals the end of a block, returns changes to the validator set
	Commit() Result                          // Commit the state and return the application Merkle root hash
}
```
And it seems a bit big to me; more than the usual replicated state machine application interface. Are all these methods necessary?  Furthermore, wouldn't it be better to split the interface into e.g. three different interfaces, one for each connection - or some other meaningful decoupling. You can always embed those interfaces into the `Application` interface. That way an application can implement the parts that are special to it, and possibly reusing other implementations for the other interfaces. (Again, pardon my ignorance for not having done a deeper investigation, but thought I'd ask...)

**Comment by melekes** [comment]
Splitting interface makes sense to me (e.g. here we could've verified that interface is satisfied https://github.com/tendermint/tendermint/blob/develop/proxy/app_conn.go#L44)

**Comment by ebuchman** [comment]
Thanks for raising this issue. Indeed, we split it up in the `proxy` package in Tendermint. 

It could be useful to split it here as well, and to put all three connection interfaces under the unified Application interface - I'd welcome that PR, especially since it shouldn't break anything :)

Additionally, we provide the `BaseApplication`, so folks can only implement/override the methods they want. 

For a full fledged real blockchain app, yes, you need all these methods.

The reason is we handle more complicated matters than your run of the mill replicated state machine:
- applications run in separate process and we need to handle crash/recovery (`Info`)
- general purpose querying of application with merkle proof (`Query`)
- Blockchain mempool style pre-filtering of transactions (`CheckTx`)
- Allow state machine to update validators with every block (`EndBlock`)

If you have ideas for how to improve this interface, we'd love to hear them!

Also, if you can point us to examples of other replicated state machine application interfaces, we'd love to see them :)

**Comment by zramsay** [comment]
closing as stale. @meling please re-open if these answers didn't suffice
