### ISSUE TITLE
Confusing Validator.pubKey content.

### ISSUE THREAD

**Issue by fomkin** [tendermint/abci#169]
In `EndBlock` response I can send `Diffs` to update validators list. `Validator` represented as `pubKey` and `power`. When I see `byte[] pubKey` I expect that it should be 32 bytes `ed25519` public key as everywhere else, but actually TM expect go-wire serialized `byte TypeEd25519 :: varint LengthOfKey :: byte[] KeyBytes`. This is a part of contract attended to be language agnostic, so I think it better to make `TypeEd25519` to proto level?

**Comment by fomkin** [comment]
In `initChain` same `Validator` has `pubKey` which is encoded as `byte TypeEd25519
:: byte[] KeyBytes`.

**Comment by ebuchman** [comment]
Thanks for this. 

Trouble is we're trying to support more than just ed25519, and since we use go-wire for pubkeys everywhere else, we'd like to use them here too. That said, protobuf is flexible enough to relax this down the road.

We definietly need to ensure we're consistent, ie. so InitChain and EndBlock validators are encoded the same way.

But we'll be retaining the go-wire type-byte prefixing. go-wire has also just been upgrading so the one-byte prefix will now become 4-bytes.

**Comment by ebuchman** [comment]
See [current](https://github.com/tendermint/tendermint/blob/develop/docs/specification/new-spec/encoding.md) and [pre amino](https://github.com/tendermint/tendermint/blob/develop/docs/specification/new-spec/pre-amino.md) in the specs :)
