### ISSUE TITLE
Documentation does not match Implementation

### ISSUE THREAD

**Issue by wolfposd** [tendermint/abci#205]
abci 0.10/tm0.16 introduced breaking changes to the protocol, as well as serialization

the current documentation does not reflect anything.

as a third party developer im totally lost on whats going on

**Comment by adrianbrink** [comment]
related #204

**Comment by wolfposd** [comment]
also the more serialization is dependent on go-wire, the less language agnostic the abci socket is.

is there a reason to not use plain protobuf in its previous form?

**Comment by ebuchman** [comment]
I'm terribly sorry about this. We're in the process of a major go-wire refactor which uses proper protobuf varints instead of the made up `<len of len><big endian len>` thing we were using before.

The same change in encoding made its way to ABCI even though new go-wire hasn't landed yet, and unfortunately proper documentation of this fell through the cracks.

I've updated the README, Changelog, and the Specification for v0.10 of the ABCI in the PR https://github.com/tendermint/abci/pull/206/files

Please see https://github.com/tendermint/abci#socket-tsp for the new description of length prefixing. 

Sorry again for this and thanks for raising it.
