### ISSUE TITLE
Abci-cli doesn't return output on check_tx or deliver_tx

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/abci#93]
It only prints something on error, nothing on success. 

If you look [at the guide](https://tendermint.com/docs/guides/abci-cli#first-example-dummy) you see:

```
> echo hello
-> data: hello

> info
-> data: {"size":0}

> commit
-> data: 0x

> deliver_tx "abc"
-> code: OK

> info
-> data: {"size":1}

> commit
-> data: 0x750502FC7E84BBD788ED589624F06CFA871845D1

> query "abc"
-> code: OK
-> data: {"index":0,"value":"abc","exists":true}
```

When I check out master / v0.5.0 (864d1f80b36b440bde030a5c18d8ac3aa8c2949d), I get the following:

```

> echo hello
-> data: hello
-> data.hex: 68656C6C6F

> info
-> data: {"size":0}
-> data.hex: 7B2273697A65223A307D

> commit

> deliver_tx "abc"

> info
-> data: {"size":1}
-> data.hex: 7B2273697A65223A317D

> commit
-> data: u�~��׈�X�$�l�E�
-> data.hex: 750502FC7E84BBD788ED589624F06CFA871845D1

> query "abc"
-> log: exists
-> height: 0
-> value: abc
-> value.hex: 616263

> check_tx "abc"

```

This seems to be a regression, since most still return values.  Also, some formats have changed and the guide needs updating.

**Comment by odeke-em** [comment]
@ethanfrey yeah as of `Mon  7 Aug 2017 14:00:43 MDT
`, the guide still uses `deliver tx "abc"` instead of `deliver_tx "abc"`(which you typed)
<img width="272" alt="screen shot 2017-08-07 at 1 59 57 pm" src="https://user-images.githubusercontent.com/4898263/29043540-d65a8b98-7b78-11e7-8d88-59e7aa7d024a.png">
<img width="367" alt="screen shot 2017-08-07 at 2 01 01 pm" src="https://user-images.githubusercontent.com/4898263/29043553-dec1df48-7b78-11e7-92d5-e69afe8e66f3.png">

and am on `abci-cli version 0.5.0`

**Comment by zramsay** [comment]
and remove empty string being printed when data is empty (see #75)
